INSERT INTO `customer` (`CustomerName`, `Address`, `City`, `PostalCode`, `Country`, `Flag`) VALUES
('Test11 Tatikonda', 'orem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scr', 'Mumbai', 'WA 123', 'Maha', '1'),
('Test12 Lakka', 'is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is', 'Brazil', '342424', 'America', '1'),
('Test13 Tatikonda', 'And a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by acciden', 'Lavasa', '324654', 'Pune', '1'),
('Test14 Gali', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable', 'Bhiwandi', '143456', 'Nashik', '1'),
('Test15 Lakka', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney', 'Nizamabad', '123456', 'Desham', '0'),
('Test16 Dasari', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable', 'Hydrabhad', '987765', 'Kamareddy', '1'),
('Test17 Dasari', 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus', 'Secendrabad', 'SA12345', 'Kamareddy', '0'),
('Test18 Gali', 'handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc', 'Desham', '123789', 'Village', '0'),
('Test19 Balap', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore', 'Solapur', '666666', 'Chutiya', '0');